[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.0",
    "pydantic>=2.12.3",
    "pytest>=8.4.2",
    "uvicorn>=0.38.0",
]
